# Generated by Django 2.1.7 on 2019-04-22 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recharge', '0002_mobile_recharge_currentuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='dth_recharge',
            name='Currentuser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
