# Generated by Django 2.1.2 on 2019-01-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_image', models.ImageField(upload_to='save_images/')),
                ('details', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
