# Generated by Django 2.1.2 on 2019-01-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_images_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Date Published'),
        ),
    ]
